### ISSUE TITLE
Adding context to unhandled exceptions

### ISSUE THREAD

**Issue by ashishmadeti** [hynek/structlog#97] opened 2016-12-15 16:08 UTC
I want all my unhandled exceptions to be logged in JSON format and also have context. So I wrote the following code:

```python
def log_exceptions_with(l):
    def excp(exctype, value, tb):
        l.error(event="exception", type=exctype.__name__,
                traceback=extract_tb(tb), value=str(value))
    sys.excepthook = excp
```

And then, in the files that I want to log unhandle exceptions:
```python
l = structlog.get_logger(attack="physical")
log_exceptions_with(l)
# ....
l = l.bind(dmg="120")
raise ValueError("Damage should be less than 100")
```

But because the logger is immutable, the event dict only contain `attack` and not `dmg`. How can I fix this or is it something that can be fixed?
Sorry, if I am asking these questions at the wrong place.

**Comment by hynek** [comment] 2016-12-19 11:04
If you want bound value to propagate transparently into some kind of global state, you could look into using threadlocals?

**Comment by ashishmadeti** [comment] 2016-12-19 12:07
Thanks! Using `structlog.threadlocal.wrap_dict(dict)` did solve my problem. I have one last question though.

In the thread-local section of your documentation, I didn't understand why did you said

> Don’t stop assigning the results of your `bind()`s and `new()`s!

Will it still be necessary if I use configure structlog with `cache_logger_on_first_use=True`?

**Comment by hynek** [comment] 2016-12-21 07:29
It’s more about performance as explained in the same point:

> Although the state is saved in a global data structure, you still need the global wrapped logger produce a real bound logger. Otherwise each log call will result in an instantiation of a temporary BoundLogger.

The main issue here is that what you get from `structlog.get_logger()` isn't the final logger but a proxy object that builds one depending on configuration.

It’s enough to assign it *once* though so you don’t use the global one.

**Closed** 2016-12-21 07:41 UTC

**Comment by antonysouthworth-halter** [comment] 2023-05-09 00:35
Is there any way for this to work if I am using structlog.contextvars.bound_contextvars as a context manager? E.g. consider the following program:

```python
import sys
import traceback

import structlog

def excepthook(etype, val, tb):
    log = structlog.getLogger(__name__)
    log.exception("unhandled exception:\n%s", traceback.format_exception(etype, val, tb))

sys.excepthook = excepthook

with structlog.contextvars.bound_contextvars(some_context="some_val"):
   raise ValueError("test")
```

What I want to have happen is the context vars `some_context="some_val"` gets included in the printout in the excepthook.

But the problem is that `sys.excepthook` is pretty much the last thing to get called prior to program exit; i.e. this happens _after_ the context is exited and therefore the context is not included in my printout 😢.

Sorry if this should have been a new thread; it's the same general question so I thought better to comment here.

**Comment by hynek** [comment] 2023-05-22 16:09
I don't think excepthook runs in context of the context manager? Pretty sure it runs separately at the end (as you note yourself).
