### ISSUE TITLE
Configure Rich tracebacks

### ISSUE THREAD

**Issue by tchapi** [hynek/structlog#496] opened 2023-03-09 09:14 UTC
Hi 👋🏼 

First of all thanks a lot for structlog! 

I have a question regarding the **Rich** traceback: is it possible to pass configuration to Rich, for instance to allow changing the width of the traceback? It seems the rich.console is initiated without the ability to pass arguments (in https://www.structlog.org/en/stable/api.html#structlog.dev.rich_traceback)

Best regards

**Comment by hynek** [comment] 2023-03-09 10:58
this seems to be a duplicate of #490, so I'll close it. pls feel free to chime in there!

**Closed by hynek** 2023-03-09 10:58 UTC
Labels: duplicate
