### ISSUE TITLE
Default configuration does not look great for Windows users

### ISSUE THREAD

**Issue by wimglenn** [hynek/structlog#232] opened 2019-11-01 17:05 UTC
It prints escape sequences to terminal.

Python 3.8.0
colorama v0.4.1
structlog v19.2.0

![screenshot](https://i.stack.imgur.com/b4xIM.png)

(in foreground is powershell, background is cmd.exe, Windows 10)

**Comment by hynek** [comment] 2019-11-02 11:33
Is this a regression? I.e. does 19.1.0 look fine everything else being equal?

**Comment by wimglenn** [comment] 2019-11-03 16:39
Yes, this is a regression.

**Comment by hynek** [comment] 2019-11-05 13:08
Yeah, me too! Could you double-check if colorama.init() is called at all please?

**Comment by wimglenn** [comment] 2019-11-05 20:49
```>>> import colorama
>>> colorama.init = lambda: print("yep!")
>>> structlog.get_logger().msg("hello")
yep!
[2m2019-11-05 14:49.13[0m [1mhello[0m```

**Comment by hynek** [comment] 2019-11-06 08:18
Oof. WTF then?

**Comment by wimglenn** [comment] 2019-11-07 02:33
It might be the print logger [needs to reacquire sys.stdout](https://github.com/hynek/structlog/blob/19.2.0/src/structlog/_loggers.py#L71) after colorama init. But I'm not a Windows user personally, so not too sure.. just guessing here

**Comment by hynek** [comment] 2019-11-07 10:02
OK just to be sure and before I start pulling people into this – could you please:

- try with Python 3.7
- double-check it doesn't happen with structlog 19.1?

thanks!

**Comment by wimglenn** [comment] 2019-11-07 19:33
```                    +--------------+--------------+
                    | Python-3.7.3 | Python-3.8.0 |
+-------------------+--------------+--------------+
| structlog==19.1.0 | ok           | ok           |
+-------------------+--------------+--------------+
| structlog==19.2.0 | bug          | bug          |
+-------------------+--------------+--------------+ 
```

**Comment by ahtik** [comment] 2020-01-19 16:12
Confirming @wimglenn observation, after moving to the colorama lazy init, `PrintLogger` `_file` assignment from `sys.stdout` comes earlier than the lazy `colorama.init()`, so the colorama StreamWrapper is never used for `write`.

The issue is only with Windows, all good with Linux, but can't debug the Linux process right now to understand the init difference.

**Comment by MarkusH** [comment] 2020-01-19 16:26
I did some debugging, and can confirm that 3b534afd4f27067502ebacd686cb190c26c6e5f8 is in fact the commit that broke the behavior. Here's why:

* Running `import structlog` imports `structlog._config` which imports `structlog.dev.ConsoleRenderer` and instantiates the latter with `colors=_has_colorama` on module level, as part of `_BUILTIN_DEFAULT_PROCESSORS`. Before said commit, that instantiation would've called `colorama.init()`. However, this call is now delayed.
* Importing `structlog` will also have imported `get_logger()`. Calling `get_logger()` will effectively return an instance of `BoundLoggerLazyProxy`.
* Calling `msg()` on the `BoundLoggerLazyProxy` instance, will cause a call to `BoundLoggerLazyProxy.__getattr__()` since `msg` isn't an attribute on that class, which will call `BoundLoggerLazyProxy.bind()`
* In `BoundLoggerLazyProxy.bind()`, `PrintLoggerFactory.__call__()` is run, instantiating a `PrintLogger` with `file=None`, causing it to store `self._file=sys.stdout`.
* The `BoundLoggerLazyProxy.bind()` returns an instance of `BoundLogger` with `_logger` being an instance of `PrintLoggerFactory`. The `BoundLogger` instance doesn't have a `msg` attribute either. Thus, `BoundLoggerBase._proxy_to_logger` will be called, which in turn eventually executes `ConsoleRenderer.__call__` which will now wrap `sys.stdout` through `colorama.init()`.

I see two ways forward:
1. Revert said commit
2. Make the `PrintLogger` lazily use `sys.stdout` when needed.

To me, reverting 3b534afd4f27067502ebacd686cb190c26c6e5f8 seems to be the more appropriate and efficient approach.

**Comment by hynek** [comment] 2020-01-21 14:12
Ugh but both are terrible. :( One looks bad on Windows, the other has an unavoidable import side-effect :(

**Closed** 2020-01-28 10:56 UTC
